name: flutter_shortener
description: A library for generating short links from multiple providers. Supported vendors:- Bit.ly
version: 0.1.1
author: Smile garg<imsmilegarg@gmail.com>
homepage: https://github.com/imsmilegarg/flutter_shortener.git

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
